services:
 app:
  build: .
  depends_on:
   - db
  volumes:
   - .:/app
  ports:
   - "8000:8000"

 db:
  image: postgres
  restart: always
  container_name: database
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgres
   POSTGRES_DB: pa-article-api
  ports:
   - "5433:5432"
  volumes:
   - pgdata:/var/lib/postgresql/data

volumes:
 pgdata:
